### ISSUE TITLE
Add support for pip 8.x

### ISSUE THREAD

**Issue by edmorley** [kennethreitz/pip-pop#10]
Currently with pip 8.1.2, the following exception is raised:
```
$ ./pip-grep foo.txt requests
Traceback (most recent call last):
  File "./pip-grep", line 81, in <module>
    main()
  File "./pip-grep", line 76, in main
    grep(**kwargs)
  File "./pip-grep", line 57, in grep
    if requirement.req.project_name in packages:
AttributeError: 'Requirement' object has no attribute 'project_name'
```
This is caused by https://github.com/pypa/pip/pull/3307 , which changed the type of `req`, such that it now has a `name` attribute rather than `project_name`.

To avoid surprises with new versions of pip, and to prevent regressions with older versions when making compatibility fixes, I've filed #9.

**Comment by edmorley** [comment]
This was fixed in heroku/heroku-buildpack-python#308 (which is currently the upstream for development) and then synced back to this repo in 4f5ebcd :-)
