### PR TITLE
Make pip-grep and pip-pop compatible with pip 8.1.2

### LINKED ISSUE #10: Add support for pip 8.x
Currently with pip 8.1.2, the following exception is raised:
```
$ ./pip-grep foo.txt requests
Traceback (most recent call last):
  File "./pip-grep", line 81, in <module>
    main()
  File "./pip-grep", line 76, in main
    grep(**kwargs)
  File "./pip-grep", line 57, in grep
    if requirement.req.project_name in packages:
AttributeError: 'Requirement' object has no attribute 'project_name'
```
This is caused by https://github.com/pypa/pip/pull/3307 , which changed the type of `req`, such that it now has a `name` attribute rather than `project_name`.

To avoid surprises with new versions of pip, and to prevent regressions with older versions when making compatibility fixes, I've filed #9.

### PR DESCRIPTION
**Pull request by edmorley**
In pip 8.1.2 the type of `requirement.req` was changed, such that it now has a `name` attribute rather than `project_name`:
pypa/pip#3307

To fix this, a name attribute is added if missing, to try and avoid having to handle the varying attribute names repeatedly later on. (Whilst a tad hacky, it seemed like the least verbose solution for `pip-diff`. Both scripts could do with quite a bit of refactoring/de-duping of code, but that's fodder for another PR.)

Passes Travis when rebased on top of #11.

See individual commits for clearer diffs.

Fixes #10.

### CODE REVIEW

**Comment by edmorley** [comment]
@kennethreitz do you know when you might be able to look at this?
Requirements files containing pip v8 hashes are currently broken on Heroku due to this, unless using a forked buildpack.

**Comment by ShaneXie** [comment]
@kennethreitz please take a look at this. got same problem on heroku. I dont want to use my folked buildpack.

**Comment by jotes** [comment]
@kennethreitz It would be awesome if you could review this patch. I'm one of those few people that love to use hashes everywhere ;->

**Comment by kennethreitz** [comment]
See https://github.com/heroku/heroku-buildpack-python/pull/308

**Comment by edmorley** [comment]
This landed in the python buildpack (which is currently the upstream for development) in heroku/heroku-buildpack-python#308, and was synced back to this repo in:
https://github.com/kennethreitz/pip-pop/commit/4f5ebcd253ec299baf0f4cb10c99d06bc52cc91f

Fixed :-)
